# Buttons:
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_GEAR_UP = 4
BUTTON_GEAR_DOWN = 5
BUTTON_R2 = 6 #R2
BUTTON_L2 = 7 #L2
BUTTON_RSB = 8 
BUTTON_LSB = 9
BUTTON_R3 = 10 #R3
BUTTON_L3 = 11

BUTTON_VOL_UP = 18
BUTTON_VOL_DOWN = 19

BUTTON__CLKWISE = 22
BUTTON_CNTRCLKWISE = 21
BUTTON_ENTER = 23

# Axes:
AXIS_STEERING_WHEEL = 0
AXIS_ACCELERATOR = 1
AXIS_BRAKE = 2
AXIS_CLUTCH = 3

# Hats:
HAT_LEFT = (-1, 0)
HAT_RIGHT = (1, 0)
HAT_UP = (0, 1)
HAT_DOWN = (0, -1)
HAT_RELEASE = (0, 0)
